name = "cardano-db-sync-docs"
compatibility_date = "2026-05-01"
compatibility_flags = ["nodejs_compat"]
main = "./dist/server/entry.mjs"
no_bundle = true

[[rules]]
type = "ESModule"
globs = ["**/*.mjs", "**/*.js"]

[assets]
directory = "./dist/client"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "dbsync"
database_id = "d62d8765-5f55-4360-b67e-80bc6e66b6a7"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1
